spring:
  application:
    name: EurekaServer
server:
  port: 9092
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone:
       http://localhost:9092/eureka/